/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_articles_categories = pgEnum('enum_articles_categories', [
  'technology',
  'design',
  'business',
  'lifestyle',
  'tutorial',
])
export const enum_articles_status = pgEnum('enum_articles_status', ['draft', 'published'])
export const enum__articles_v_version_categories = pgEnum('enum__articles_v_version_categories', [
  'technology',
  'design',
  'business',
  'lifestyle',
  'tutorial',
])
export const enum__articles_v_version_status = pgEnum('enum__articles_v_version_status', [
  'draft',
  'published',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => ({
    _orderIdx: index('users_sessions_order_idx').on(columns._order),
    _parentIDIdx: index('users_sessions_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => ({
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
    users_email_idx: uniqueIndex('users_email_idx').on(columns.email),
  }),
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
  },
  (columns) => ({
    media_updated_at_idx: index('media_updated_at_idx').on(columns.updatedAt),
    media_created_at_idx: index('media_created_at_idx').on(columns.createdAt),
    media_filename_idx: uniqueIndex('media_filename_idx').on(columns.filename),
  }),
)

export const articles_categories = pgTable(
  'articles_categories',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_articles_categories('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => ({
    orderIdx: index('articles_categories_order_idx').on(columns.order),
    parentIdx: index('articles_categories_parent_idx').on(columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [articles.id],
      name: 'articles_categories_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const articles = pgTable(
  'articles',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    author: integer('author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    status: enum_articles_status('status').default('draft'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    excerpt: varchar('excerpt'),
    content: jsonb('content'),
    readingTime: numeric('reading_time'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_articles_status('_status').default('draft'),
  },
  (columns) => ({
    articles_slug_idx: uniqueIndex('articles_slug_idx').on(columns.slug),
    articles_author_idx: index('articles_author_idx').on(columns.author),
    articles_featured_image_idx: index('articles_featured_image_idx').on(columns.featuredImage),
    articles_updated_at_idx: index('articles_updated_at_idx').on(columns.updatedAt),
    articles_created_at_idx: index('articles_created_at_idx').on(columns.createdAt),
    articles__status_idx: index('articles__status_idx').on(columns._status),
  }),
)

export const articles_texts = pgTable(
  'articles_texts',
  {
    id: serial('id').primaryKey(),
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    text: varchar('text'),
  },
  (columns) => ({
    orderParentIdx: index('articles_texts_order_parent_idx').on(columns.order, columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [articles.id],
      name: 'articles_texts_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const _articles_v_version_categories = pgTable(
  '_articles_v_version_categories',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum__articles_v_version_categories('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => ({
    orderIdx: index('_articles_v_version_categories_order_idx').on(columns.order),
    parentIdx: index('_articles_v_version_categories_parent_idx').on(columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_articles_v.id],
      name: '_articles_v_version_categories_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const _articles_v = pgTable(
  '_articles_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => articles.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_author: integer('version_author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    version_status: enum__articles_v_version_status('version_status').default('draft'),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_featuredImage: integer('version_featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_excerpt: varchar('version_excerpt'),
    version_content: jsonb('version_content'),
    version_readingTime: numeric('version_reading_time'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__articles_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => ({
    _articles_v_parent_idx: index('_articles_v_parent_idx').on(columns.parent),
    _articles_v_version_version_slug_idx: index('_articles_v_version_version_slug_idx').on(
      columns.version_slug,
    ),
    _articles_v_version_version_author_idx: index('_articles_v_version_version_author_idx').on(
      columns.version_author,
    ),
    _articles_v_version_version_featured_image_idx: index(
      '_articles_v_version_version_featured_image_idx',
    ).on(columns.version_featuredImage),
    _articles_v_version_version_updated_at_idx: index(
      '_articles_v_version_version_updated_at_idx',
    ).on(columns.version_updatedAt),
    _articles_v_version_version_created_at_idx: index(
      '_articles_v_version_version_created_at_idx',
    ).on(columns.version_createdAt),
    _articles_v_version_version__status_idx: index('_articles_v_version_version__status_idx').on(
      columns.version__status,
    ),
    _articles_v_created_at_idx: index('_articles_v_created_at_idx').on(columns.createdAt),
    _articles_v_updated_at_idx: index('_articles_v_updated_at_idx').on(columns.updatedAt),
    _articles_v_latest_idx: index('_articles_v_latest_idx').on(columns.latest),
  }),
)

export const _articles_v_texts = pgTable(
  '_articles_v_texts',
  {
    id: serial('id').primaryKey(),
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    text: varchar('text'),
  },
  (columns) => ({
    orderParentIdx: index('_articles_v_texts_order_parent_idx').on(columns.order, columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_articles_v.id],
      name: '_articles_v_texts_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug,
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    articlesID: integer('articles_id'),
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx',
    ).on(columns.usersID),
    payload_locked_documents_rels_media_id_idx: index(
      'payload_locked_documents_rels_media_id_idx',
    ).on(columns.mediaID),
    payload_locked_documents_rels_articles_id_idx: index(
      'payload_locked_documents_rels_articles_id_idx',
    ).on(columns.articlesID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    articlesIdFk: foreignKey({
      columns: [columns['articlesID']],
      foreignColumns: [articles.id],
      name: 'payload_locked_documents_rels_articles_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_users_id_idx: index('payload_preferences_rels_users_id_idx').on(
      columns.usersID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const homepage = pgTable('homepage', {
  id: serial('id').primaryKey(),
  heroTitle: varchar('hero_title').notNull(),
  bio: varchar('bio'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const homepage_rels = pgTable(
  'homepage_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    articlesID: integer('articles_id'),
  },
  (columns) => ({
    order: index('homepage_rels_order_idx').on(columns.order),
    parentIdx: index('homepage_rels_parent_idx').on(columns.parent),
    pathIdx: index('homepage_rels_path_idx').on(columns.path),
    homepage_rels_articles_id_idx: index('homepage_rels_articles_id_idx').on(columns.articlesID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [homepage.id],
      name: 'homepage_rels_parent_fk',
    }).onDelete('cascade'),
    articlesIdFk: foreignKey({
      columns: [columns['articlesID']],
      foreignColumns: [articles.id],
      name: 'homepage_rels_articles_fk',
    }).onDelete('cascade'),
  }),
)

export const about = pgTable(
  'about',
  {
    id: serial('id').primaryKey(),
    content: jsonb('content').notNull(),
    profileImage: integer('profile_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => ({
    about_profile_image_idx: index('about_profile_image_idx').on(columns.profileImage),
  }),
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_articles_categories = relations(articles_categories, ({ one }) => ({
  parent: one(articles, {
    fields: [articles_categories.parent],
    references: [articles.id],
    relationName: 'categories',
  }),
}))
export const relations_articles_texts = relations(articles_texts, ({ one }) => ({
  parent: one(articles, {
    fields: [articles_texts.parent],
    references: [articles.id],
    relationName: '_texts',
  }),
}))
export const relations_articles = relations(articles, ({ one, many }) => ({
  author: one(users, {
    fields: [articles.author],
    references: [users.id],
    relationName: 'author',
  }),
  featuredImage: one(media, {
    fields: [articles.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
  categories: many(articles_categories, {
    relationName: 'categories',
  }),
  _texts: many(articles_texts, {
    relationName: '_texts',
  }),
}))
export const relations__articles_v_version_categories = relations(
  _articles_v_version_categories,
  ({ one }) => ({
    parent: one(_articles_v, {
      fields: [_articles_v_version_categories.parent],
      references: [_articles_v.id],
      relationName: 'version_categories',
    }),
  }),
)
export const relations__articles_v_texts = relations(_articles_v_texts, ({ one }) => ({
  parent: one(_articles_v, {
    fields: [_articles_v_texts.parent],
    references: [_articles_v.id],
    relationName: '_texts',
  }),
}))
export const relations__articles_v = relations(_articles_v, ({ one, many }) => ({
  parent: one(articles, {
    fields: [_articles_v.parent],
    references: [articles.id],
    relationName: 'parent',
  }),
  version_author: one(users, {
    fields: [_articles_v.version_author],
    references: [users.id],
    relationName: 'version_author',
  }),
  version_featuredImage: one(media, {
    fields: [_articles_v.version_featuredImage],
    references: [media.id],
    relationName: 'version_featuredImage',
  }),
  version_categories: many(_articles_v_version_categories, {
    relationName: 'version_categories',
  }),
  _texts: many(_articles_v_texts, {
    relationName: '_texts',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    articlesID: one(articles, {
      fields: [payload_locked_documents_rels.articlesID],
      references: [articles.id],
      relationName: 'articles',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_homepage_rels = relations(homepage_rels, ({ one }) => ({
  parent: one(homepage, {
    fields: [homepage_rels.parent],
    references: [homepage.id],
    relationName: '_rels',
  }),
  articlesID: one(articles, {
    fields: [homepage_rels.articlesID],
    references: [articles.id],
    relationName: 'articles',
  }),
}))
export const relations_homepage = relations(homepage, ({ many }) => ({
  _rels: many(homepage_rels, {
    relationName: '_rels',
  }),
}))
export const relations_about = relations(about, ({ one }) => ({
  profileImage: one(media, {
    fields: [about.profileImage],
    references: [media.id],
    relationName: 'profileImage',
  }),
}))

type DatabaseSchema = {
  enum_articles_categories: typeof enum_articles_categories
  enum_articles_status: typeof enum_articles_status
  enum__articles_v_version_categories: typeof enum__articles_v_version_categories
  enum__articles_v_version_status: typeof enum__articles_v_version_status
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  articles_categories: typeof articles_categories
  articles: typeof articles
  articles_texts: typeof articles_texts
  _articles_v_version_categories: typeof _articles_v_version_categories
  _articles_v: typeof _articles_v
  _articles_v_texts: typeof _articles_v_texts
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  homepage: typeof homepage
  homepage_rels: typeof homepage_rels
  about: typeof about
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_articles_categories: typeof relations_articles_categories
  relations_articles_texts: typeof relations_articles_texts
  relations_articles: typeof relations_articles
  relations__articles_v_version_categories: typeof relations__articles_v_version_categories
  relations__articles_v_texts: typeof relations__articles_v_texts
  relations__articles_v: typeof relations__articles_v
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_homepage_rels: typeof relations_homepage_rels
  relations_homepage: typeof relations_homepage
  relations_about: typeof relations_about
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
